# Generated by Django 5.1.6 on 2025-02-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valores_Convertidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('moeda_de_origem', models.CharField(max_length=3)),
                ('moeda_destino', models.CharField(max_length=3)),
                ('valor_de_origem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_destino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
